tasks:
  - type: docker-build
    image: glance-github-graph
    platforms:
      - linux/arm64
      - linux/amd64
    # qemu: true
    auto:
      - source: push
        has_tag: true
        tag_source: tag
      - source: push
        has_tag: true
        tag_source: latest
    context: glance-github-graph
    file: Dockerfile
    registries:
      - gitlab
      - docker-hub
